package com.doAI.backend.model;

public enum LocationEnum {
    CENTRO_ESPERANCA_SOLIDARIA,
    NUCLEO_DE_APOIO_COMUNITARIO,
    CASA_DA_BONDADE,
    PONTES_DA_COMPAIXAO,
    INSTITUTO_CORACOES_UNIDOS
}